### PR TITLE
Add PowerBy Simpeg badge

### PR DESCRIPTION
**Pull request by fourndo**
Attempt to add badge

### CODE REVIEW

**Comment by rowanc1** [comment]
https://github.com/simpeg/simpeg/blob/master/docs/conf.py#L268

**Comment by fourndo** [comment]
Excellent, thanks man.
Let see...

**Comment by fourndo** [comment]
@rowanc1 Can you check the function when you have sec?

**Comment by rowanc1** [comment]
Maybe sphinx has updated? @lheagy any thoughts?

**Comment by lheagy** [comment]
no, this is a sphinx warning. on em, simpeg docs, we have an over-ride. I will push a patch

**Comment by fourndo** [comment]
@lheagy :+1: oh yea
capture

**Pull request merged**
